environment:
  matrix:
    - PYTHON: "C:\\Python36\\python.exe"

install:
  - "%PYTHON% -m pip install -r requirements.txt"
  - "%PYTHON% manage.py migrate"

build: off

before_test:
  - set PYTHONIOENCODING=utf-8

test_script:
  - "%PYTHON% manage.py test shift_report"
