jobs:
  include:
    - language: python
      python: 2.7
      install: pip install -r requirements.txt
      script:
        - python manage.py migrate
        - python manage.py test shift_report
    - language: python
      python: 3.6
      install: pip install -r requirements.txt
      script:
        - python manage.py migrate
        - python manage.py test shift_report
    - language: node_js
      node_js: 8.6
      before_script:
        - npm install -g grunt-cli
        - npm install -g bower
        - cd webapp
        - npm install
        - bower install
      script: grunt dist
