# Generated by Django 2.0.1 on 2018-01-28 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('assigned_team', models.CharField(max_length=128)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.IntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_report.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('unit', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField(primary_key=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('name', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('date', models.DateField(db_index=True, primary_key=True, serialize=False, unique=True)),
                ('money_from_shares', models.IntegerField(default=0)),
                ('money_from_cheques', models.IntegerField(default=0)),
                ('money_from_cash', models.IntegerField(default=0)),
                ('envelope_number', models.IntegerField(default=0)),
                ('almost_missing_products', models.ManyToManyField(related_name='almost_missing', to='shift_report.Product')),
                ('disposed_products', models.ManyToManyField(related_name='disposed', to='shift_report.Product')),
                ('leaving_members', models.ManyToManyField(related_name='leaving', to='shift_report.Member')),
                ('members', models.ManyToManyField(through='shift_report.MemberShift', to='shift_report.Member')),
                ('money_at_shift_end', models.ManyToManyField(related_name='shift_end', to='shift_report.Money')),
                ('money_at_shift_start', models.ManyToManyField(related_name='shift_start', to='shift_report.Money')),
                ('new_members', models.ManyToManyField(related_name='new', to='shift_report.Member')),
            ],
        ),
        migrations.AddField(
            model_name='membershift',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_report.Role'),
        ),
        migrations.AddField(
            model_name='membershift',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_report.Shift'),
        ),
        migrations.AddField(
            model_name='conclusions',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_report.Shift'),
        ),
    ]
