# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_report', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='leaving_members',
            field=models.ManyToManyField(related_name='leaving', to='shift_report.Member'),
        ),
        migrations.AddField(
            model_name='shift',
            name='new_members',
            field=models.ManyToManyField(related_name='new', to='shift_report.Member'),
        ),
    ]
