# Generated by Django 2.0.4 on 2018-04-23 15:34

from django.db import migrations, models
import django.db.models.deletion
import shift_report.models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='envelope_number',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='money_from_cash',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='money_from_cheques',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cache',
            name='money_from_shares',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='shift',
            name='cache',
            field=models.ForeignKey(default=shift_report.models.Cache.empty, null=True, on_delete=django.db.models.deletion.CASCADE, to='shift_report.Cache'),
        ),
    ]
