# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_report', '0002_auto_20171012_0955'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conclusions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('assigned_team', models.CharField(max_length=128)),
                ('done', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='shift',
            name='envelope_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='money_from_cash',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='money_from_cheques',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shift',
            name='money_from_shares',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
        migrations.AddField(
            model_name='conclusions',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_report.Shift'),
        ),
        migrations.AddField(
            model_name='shift',
            name='almost_missing_products',
            field=models.ManyToManyField(related_name='almost_missing', to='shift_report.Product'),
        ),
        migrations.AddField(
            model_name='shift',
            name='disposed_products',
            field=models.ManyToManyField(related_name='disposed', to='shift_report.Product'),
        ),
        migrations.AddField(
            model_name='shift',
            name='money_at_shift_end',
            field=models.ManyToManyField(related_name='shift_end', to='shift_report.Money'),
        ),
        migrations.AddField(
            model_name='shift',
            name='money_at_shift_start',
            field=models.ManyToManyField(related_name='shift_start', to='shift_report.Money'),
        ),
    ]
