# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_report', '0003_auto_20171012_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='money',
            name='id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.RemoveField(
            model_name='role',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='id',
        ),
        migrations.AlterField(
            model_name='money',
            name='amount',
            field=models.IntegerField(primary_key=True),
        ),
        migrations.AlterField(
            model_name='money',
            name='unit',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateField(db_index=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
